### PR TITLE
Update Log file to MD format

### PR DESCRIPTION
**Pull request by sohamdeogaonkar**

### CODE REVIEW

**Comment by bots-business** [comment]
+2 EL

**Comment by bots-business** [comment]
Need resolve merge conflict. 
Please update logfile with new data

+3 EL after merge

**Comment by sohamdeogaonkar** [comment]
what do u mean to say 
@bots-business 

and it is say i need write acces to resolve  conflict

**Comment by bots-business** [comment]
LogFile changed. Need update with your table for all data

**Pull request closed without merging**
